import Link from "next/link";
import { FC } from "react";
import { Ticket } from "../../interfaces";

// Generated by https://quicktype.io

export const OrderCard: FC<Ticket> = ({
  id,
  ticketItems,
  totalAmount,
  status,
  createdAt,
}) => {
  return (
    <Link href={`/profile/orders/${id}`} passHref>
      <article className="bg-white p-4 rounded-2xl border space-y-2 cursor-pointer hover:scale-95 transition-all active:bg-shade shadow-sm">
        <div className="flex flex-row justify-between items-center">
          <h1 className="font-semibold text-base">#{id.split("-")[0]}</h1>
          <div className="bg-secondary text-white p-1 px-2 rounded-full text-xs font-bold">
            {"status"}
          </div>
        </div>
        <div className="text-xs">{createdAt}</div>
        <div className="text-sm">
          {ticketItems.map((item) => (
            <div key={item.id + item.quantity + item.totalAmount}>
              {item.quantity} x {item.product.name}
            </div>
          ))}
        </div>
        <hr />
        <div className="text-sm">${parseFloat(totalAmount).toFixed(2)}</div>
      </article>
    </Link>
  );
};

export default OrderCard;
