name: Next CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Deploy Nextjs client
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        passphrase: ${{secrets.SSH_PASSPHRASE}}
        script: |
          cd /var/www/client
          git pull origin main
          pm2 delete next-client
          node -v
          yarn build
          pm2 start yarn --name "next-client" -- start
          pm2 save
          echo 'Deployment succesful to digital ocean'